name: Nix Development Environment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Enable Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Check flake evaluates on all systems
        run: nix flake check --all-systems

      - name: Verify devShell activates
        run: nix develop